### ISSUE TITLE
Running into Docker API connection issue

### ISSUE THREAD

**Issue by darinsmi** [oncyberblog/whaler#4]
Thanks for developing this project! 
I'm attempting to set it up in a Ubuntu EC2 in AWS and am running into a bit of a problem. When running reset-redeploy.sh or just `docker-compose up` manually, I get the following error:
`
whaler        | Traceback (most recent call last):
whaler        |   File "./app/Whaler.py", line 121, in <module>
whaler        |     Whaler().run()
whaler        |   File "./app/Whaler.py", line 18, in __init__
whaler        |     self.victimCli=docker.DockerClient(base_url=Configuration().get("dockerDaemonVictimUrl"))
whaler        |   File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 45, in __init__
whaler        |     self.api = APIClient(*args, **kwargs)
whaler        |   File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 197, in __init__
whaler        |     self._version = self._retrieve_server_version()
whaler        |   File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
whaler        |     'Error while fetching server API version: {0}'.format(e)
whaler        | docker.errors.DockerException: Error while fetching server API version: HTTPConnectionPool(host='whaler_victim', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92d7d3fb10>: Failed to establish a new connection: [Errno -3] Try again',))`

I found this issue, https://github.com/oncyberblog/whaler/issues/3, and though my error is a bit different I thought it looked similar enough that I tried the same fix and added the line recommended to disable TLS. However, no change, I still get the same error. 
Any ideas? It looks to me like the whaler_victim is never really getting started within the whaler_agent, perhaps.

**Comment by amitgadhave17** [comment]
@dacelbot I am also facing the same issue, did you able to solve this issue?
